# Language
language: ruby

# Cache dependencies for faster builds
cache: true

# whitelist
branches:
  only:
    - gh-pages

# Version Numbers
#- 2.0.0, 2.1.2
rvm:
  - 2.2.0

# Jobs to test on the script
script:
  - bundle exec jekyll hyde  --trace
  - bundle exec jekyll build --trace

# Notifications
notifications:
  email:
    on_success: change
    on_failure: always