# Site settings
title: "Yale Demos"
email: "demos@dwighthall.org"
username: YaleDemos
description: "This website is published by Yale College students and Yale University is not responsible for its contents."
baseurl: "/demos"
url: "http://jasonkliu.github.io"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md, Gemfile, Gemfile.lock, prepare_upload.sh]
